// Sanitized structure from the observed Ziff Davis OneTrust integration.
// Provider-generated user IDs and unrelated page content are excluded.
export const groupedNotice=(options={})=>{
 const checked=options.on===false?'':'checked';
 const child=(id,name)=>`<li class="ot-subgrp" data-optanongroupid="${id}"><h5>${name}</h5><input type="checkbox" class="cookie-subgroup-handler" id="ot-sub-group-id-${id}" data-optanongroupid="${id}" aria-label="${name}" ${checked}></li>`;
 return `<!doctype html><html><head><style>[hidden]{display:none!important}#onetrust-banner-sdk,#onetrust-pc-sdk{position:fixed;bottom:0;padding:20px;background:white}#ot-group-id-OSSTA_BG{opacity:0;position:absolute;width:1px}label{display:inline-block;padding:12px}.ot-subgrps{display:none}</style></head><body><main><h1>Article</h1><button id="user">Open details</button></main><div id="onetrust-banner-sdk" role="dialog"><p>Your privacy choices. Cookies and tracking.</p><a class="zdcOpenPc" href="#">Subject to your privacy choices</a><button type="button" id="onetrust-accept-btn-handler">Close</button><button type="button" id="native-close" class="onetrust-close-btn-handler">Close</button></div><div id="onetrust-pc-sdk" role="dialog" hidden><div id="ot-pc-content"><section class="ot-cat-grp"><div class="ot-cat-item" data-optanongroupid="C0001"><h4 id="ot-header-id-C0001">Strictly Necessary Cookies</h4><div class="ot-always-active">Always Active</div></div><div class="ot-cat-item" data-optanongroupid="OSSTA_BG"><h4 id="ot-header-id-OSSTA_BG">Targeted Advertising</h4><input type="checkbox" class="category-switch-handler" id="ot-group-id-OSSTA_BG" data-optanongroupid="OSSTA_BG" ${checked}><label for="ot-group-id-OSSTA_BG">Targeted Advertising</label><ul class="ot-subgrps">${child('C0004','Targeting Cookies')}${child('C0002','Performance Cookies')}</ul></div></section></div><section id="ot-pc-lst" style="display:none"><input id="vendor-search-handler" type="text"></section><button type="button" class="save-preference-btn-handler onetrust-close-btn-handler">Confirm My Choices</button><button type="button" id="accept-recommended-btn-handler">Allow All</button><iframe class="ot-text-resize" sandbox="allow-same-origin" title="onetrust-text-resize" style="position:absolute;top:-50000px;width:100em" aria-hidden="true"></iframe></div><section id="cookie-banner" role="dialog" style="position:fixed;top:0"><p>Optional cookies</p><button type="button" onclick="this.parentElement.remove()">Reject all</button></section><script>
 window.actions=[];const bar=document.querySelector('#onetrust-banner-sdk'),panel=document.querySelector('#onetrust-pc-sdk'),parent=document.querySelector('#ot-group-id-OSSTA_BG');
 document.querySelector('.zdcOpenPc').onclick=e=>{e.preventDefault();actions.push('open');${options.openNoop?'':"panel.hidden=false;bar.hidden=true;"}${options.afterOpen||''}};
 parent.onchange=()=>{actions.push('parent:'+parent.checked);${options.stuck?'':"for(const child of panel.querySelectorAll('.cookie-subgroup-handler'))child.checked=parent.checked;"}${options.afterToggle||''}};
 document.querySelector('.save-preference-btn-handler').onclick=()=>{actions.push('save');${options.saveNoop?'':"panel.hidden=true;bar.hidden=true;document.cookie='test-choice='+parent.checked+'; path=/';"}};
 for(const id of ['onetrust-accept-btn-handler','accept-recommended-btn-handler'])document.getElementById(id).onclick=()=>actions.push('accept');
 document.querySelector('#native-close').onclick=()=>{actions.push('native-close');panel.hidden=true;bar.hidden=true;};
 ${options.setup||''}
 </script></body></html>`;
};
